# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brlinkz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='fav',
            field=models.NullBooleanField(default=False),
        ),
    ]
